# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_calibstatus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19message_calibstatus.proto\x12\x0crbk.protocol\"\xa3\x01\n\x13Message_CalibStatus\x12=\n\x06status\x18\x07 \x01(\x0e\x32-.rbk.protocol.Message_CalibStatus.CalibStatus\x12\x0c\n\x04\x64\x65sc\x18\x08 \x01(\t\"?\n\x0b\x43\x61libStatus\x12\x08\n\x04None\x10\x00\x12\x0b\n\x07Running\x10\x01\x12\r\n\tCompleted\x10\x02\x12\n\n\x06\x46\x61iled\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_calibstatus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_CALIBSTATUS']._serialized_start=44
  _globals['_MESSAGE_CALIBSTATUS']._serialized_end=207
  _globals['_MESSAGE_CALIBSTATUS_CALIBSTATUS']._serialized_start=144
  _globals['_MESSAGE_CALIBSTATUS_CALIBSTATUS']._serialized_end=207
# @@protoc_insertion_point(module_scope)
