# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_rfid.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_header_pb2 as message__header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12message_rfid.proto\x12\x0crbk.protocol\x1a\x14message_header.proto\"m\n\x10Message_RFIDNode\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12,\n\x06header\x18\x03 \x01(\x0b\x32\x1c.rbk.protocol.Message_Header\x12\x10\n\x08strength\x18\x04 \x01(\r\"B\n\x0cMessage_RFID\x12\x32\n\nrfid_nodes\x18\x01 \x03(\x0b\x32\x1e.rbk.protocol.Message_RFIDNodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_rfid_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_RFIDNODE']._serialized_start=58
  _globals['_MESSAGE_RFIDNODE']._serialized_end=167
  _globals['_MESSAGE_RFID']._serialized_start=169
  _globals['_MESSAGE_RFID']._serialized_end=235
# @@protoc_insertion_point(module_scope)
