# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_dmx512.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14message_dmx512.proto\x12\x0crbk.protocol\"\x8f\x01\n\x0eMessage_Dmx512\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0f\n\x07\x62\x61ttery\x18\x02 \x01(\r\x12\x0f\n\x07\x63olor_r\x18\x03 \x01(\r\x12\x0f\n\x07\x63olor_g\x18\x04 \x01(\r\x12\x0f\n\x07\x63olor_b\x18\x05 \x01(\r\x12\x0f\n\x07\x63olor_w\x18\x06 \x01(\r\x12\x1a\n\x12turn_left_or_right\x18\x07 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_dmx512_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_DMX512']._serialized_start=39
  _globals['_MESSAGE_DMX512']._serialized_end=182
# @@protoc_insertion_point(module_scope)
