# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_distancesensor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_header_pb2 as message__header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cmessage_distancesensor.proto\x12\x0crbk.protocol\x1a\x14message_header.proto\"\x82\x02\n\x14Message_DistanceNode\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.rbk.protocol.Message_Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x0c\n\x04\x64ist\x18\x04 \x01(\x02\x12\r\n\x05valid\x18\x05 \x01(\x08\x12\r\n\x05pos_x\x18\x06 \x01(\x02\x12\r\n\x05pos_y\x18\x07 \x01(\x02\x12\x11\n\tpos_angle\x18\x08 \x01(\x02\x12\x10\n\x08\x61perture\x18\t \x01(\x02\x12\x11\n\tforbidden\x18\n \x01(\x08\x12\x12\n\ncan_router\x18\x0b \x01(\r\x12\r\n\x05rs485\x18\x0c \x01(\r\x12\x0c\n\x04RSSI\x18\r \x01(\r\"J\n\x16Message_DistanceSensor\x12\x30\n\x04node\x18\x01 \x03(\x0b\x32\".rbk.protocol.Message_DistanceNodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_distancesensor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_DISTANCENODE']._serialized_start=69
  _globals['_MESSAGE_DISTANCENODE']._serialized_end=327
  _globals['_MESSAGE_DISTANCESENSOR']._serialized_start=329
  _globals['_MESSAGE_DISTANCESENSOR']._serialized_end=403
# @@protoc_insertion_point(module_scope)
