# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_rv_storage_status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmessage_rv_storage_status.proto\x12\x13rbk.protocol.vision\"\xab\x01\n\x0fMessage_BinPose\x12\x10\n\x08\x62in_type\x18\x01 \x01(\t\x12\r\n\x05layer\x18\x02 \x01(\x05\x12\t\n\x01x\x18\x03 \x01(\x02\x12\t\n\x01y\x18\x04 \x01(\x02\x12\t\n\x01z\x18\x05 \x01(\x02\x12\x0c\n\x04roll\x18\x06 \x01(\x02\x12\r\n\x05pitch\x18\x07 \x01(\x02\x12\x0b\n\x03yaw\x18\x08 \x01(\x02\x12\r\n\x05width\x18\t \x01(\x02\x12\x0e\n\x06height\x18\n \x01(\x02\x12\r\n\x05\x64\x65pth\x18\x0b \x01(\x02\"\'\n\rMessage_Point\x12\n\n\x02x0\x18\x01 \x01(\x05\x12\n\n\x02y0\x18\x02 \x01(\x05\"J\n\x14Message_StorageShape\x12\x32\n\x06points\x18\x01 \x03(\x0b\x32\".rbk.protocol.vision.Message_Point\"\xf4\x01\n\x11Message_BinStatus\x12\x37\n\tbin_poses\x18\x01 \x03(\x0b\x32$.rbk.protocol.vision.Message_BinPose\x12\x0e\n\x06layers\x18\x02 \x01(\x05\x12\x15\n\rstorage_group\x18\x03 \x01(\t\x12\x12\n\nstorage_id\x18\x04 \x01(\t\x12\x18\n\x10storage_occupied\x18\x05 \x01(\x08\x12\x17\n\x0fstorage_shelter\x18\x06 \x01(\x08\x12\x38\n\x05shape\x18\x07 \x01(\x0b\x32).rbk.protocol.vision.Message_StorageShape\"L\n\x0eMessage_Status\x12:\n\nbin_status\x18\x01 \x03(\x0b\x32&.rbk.protocol.vision.Message_BinStatus\"Z\n\x15Message_StorageStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x33\n\x06status\x18\x02 \x01(\x0b\x32#.rbk.protocol.vision.Message_Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_rv_storage_status_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_BINPOSE']._serialized_start=57
  _globals['_MESSAGE_BINPOSE']._serialized_end=228
  _globals['_MESSAGE_POINT']._serialized_start=230
  _globals['_MESSAGE_POINT']._serialized_end=269
  _globals['_MESSAGE_STORAGESHAPE']._serialized_start=271
  _globals['_MESSAGE_STORAGESHAPE']._serialized_end=345
  _globals['_MESSAGE_BINSTATUS']._serialized_start=348
  _globals['_MESSAGE_BINSTATUS']._serialized_end=592
  _globals['_MESSAGE_STATUS']._serialized_start=594
  _globals['_MESSAGE_STATUS']._serialized_end=670
  _globals['_MESSAGE_STORAGESTATUS']._serialized_start=672
  _globals['_MESSAGE_STORAGESTATUS']._serialized_end=762
# @@protoc_insertion_point(module_scope)
