# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_adcollisionsensor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_header_pb2 as message__header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmessage_adcollisionsensor.proto\x12\x0crbk.protocol\x1a\x14message_header.proto\"\xe2\x02\n\x17Message_ADCollisionNode\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.rbk.protocol.Message_Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x0b\n\x03\x61\x64\x63\x18\x04 \x01(\x02\x12\x10\n\x08pressure\x18\x05 \x01(\x02\x12\r\n\x05valid\x18\x06 \x01(\x08\x12\x11\n\tcollision\x18\x07 \x01(\x08\x12\t\n\x01x\x18\x08 \x01(\x02\x12\t\n\x01y\x18\t \x01(\x02\x12\t\n\x01z\x18\n \x01(\x02\x12\x0b\n\x03yaw\x18\x0b \x01(\x02\x12\x11\n\tforbidden\x18\x0c \x01(\x08\x12\x12\n\ncan_router\x18\r \x01(\r\x12\r\n\x05rs485\x18\x0e \x01(\r\x12\r\n\x05shape\x18\x0f \x01(\t\x12\x0f\n\x07mindist\x18\x10 \x01(\x01\x12\x0f\n\x07maxdist\x18\x11 \x01(\x01\x12\r\n\x05range\x18\x12 \x01(\x01\x12\x0c\n\x04posx\x18\x13 \x03(\x01\x12\x0c\n\x04posy\x18\x14 \x03(\x01\"P\n\x19Message_ADCollisionSensor\x12\x33\n\x04node\x18\x01 \x03(\x0b\x32%.rbk.protocol.Message_ADCollisionNodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_adcollisionsensor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_ADCOLLISIONNODE']._serialized_start=72
  _globals['_MESSAGE_ADCOLLISIONNODE']._serialized_end=426
  _globals['_MESSAGE_ADCOLLISIONSENSOR']._serialized_start=428
  _globals['_MESSAGE_ADCOLLISIONSENSOR']._serialized_end=508
# @@protoc_insertion_point(module_scope)
