# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_rbk4_image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_rbk4_header_pb2 as message__rbk4__header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18message_rbk4_image.proto\x12\rrbk4.protocol\x1a\x19message_rbk4_header.proto\"y\n\rMessage_Image\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.rbk4.protocol.Message_Header\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\"p\n\x12Message_DepthImage\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.rbk4.protocol.Message_Header\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_rbk4_image_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_IMAGE']._serialized_start=70
  _globals['_MESSAGE_IMAGE']._serialized_end=191
  _globals['_MESSAGE_DEPTHIMAGE']._serialized_start=193
  _globals['_MESSAGE_DEPTHIMAGE']._serialized_end=305
# @@protoc_insertion_point(module_scope)
