# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_tracking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16message_tracking.proto\x12\x0crbk.protocol\"\xb4\x01\n\x16Message_TrackingStatus\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12L\n\x0ftracking_status\x18\x03 \x01(\x0e\x32\x33.rbk.protocol.Message_TrackingStatus.TrackingStatus\"6\n\x0eTrackingStatus\x12\x0c\n\x08Tracking\x10\x00\x12\x08\n\x04Lose\x10\x01\x12\x0c\n\x08NoTarget\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_tracking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_TRACKINGSTATUS']._serialized_start=41
  _globals['_MESSAGE_TRACKINGSTATUS']._serialized_end=221
  _globals['_MESSAGE_TRACKINGSTATUS_TRACKINGSTATUS']._serialized_start=167
  _globals['_MESSAGE_TRACKINGSTATUS_TRACKINGSTATUS']._serialized_end=221
# @@protoc_insertion_point(module_scope)
