# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_ultrasonic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_header_pb2 as message__header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18message_ultrasonic.proto\x12\x0crbk.protocol\x1a\x14message_header.proto\"\x8b\x02\n\x11Message_UltraNode\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x64ist\x18\x02 \x01(\x01\x12\r\n\x05valid\x18\x03 \x01(\x08\x12\r\n\x05pos_x\x18\x04 \x01(\x01\x12\r\n\x05pos_y\x18\x05 \x01(\x01\x12\x11\n\tpos_angle\x18\x06 \x01(\x01\x12\x10\n\x08max_dist\x18\x07 \x01(\x01\x12\x10\n\x08min_dist\x18\x08 \x01(\x01\x12\x10\n\x08\x61perture\x18\t \x01(\x01\x12\x11\n\tforbidden\x18\n \x01(\x08\x12,\n\x06header\x18\x0b \x01(\x0b\x32\x1c.rbk.protocol.Message_Header\x12\x16\n\x0eoffset_time_ms\x18\x0c \x01(\x05\x12\r\n\x05pos_z\x18\r \x01(\x01\"i\n\x12Message_Ultrasonic\x12\r\n\x05\x63ycle\x18\x01 \x01(\r\x12.\n\x05nodes\x18\x02 \x03(\x0b\x32\x1f.rbk.protocol.Message_UltraNode\x12\x14\n\x0c\x62\x61se_time_ns\x18\x03 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_ultrasonic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_ULTRANODE']._serialized_start=65
  _globals['_MESSAGE_ULTRANODE']._serialized_end=332
  _globals['_MESSAGE_ULTRASONIC']._serialized_start=334
  _globals['_MESSAGE_ULTRASONIC']._serialized_end=439
# @@protoc_insertion_point(module_scope)
