# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_fallingdown.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19message_fallingdown.proto\x12\x0crbk.protocol\"o\n\x13Message_FallingNode\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x64ist\x18\x02 \x01(\x01\x12\r\n\x05valid\x18\x03 \x01(\x08\x12\r\n\x05pos_x\x18\x04 \x01(\x01\x12\r\n\x05pos_y\x18\x05 \x01(\x01\x12\x11\n\tpos_angle\x18\x06 \x01(\x01\"V\n\x13Message_Fallingdown\x12\r\n\x05\x63ycle\x18\x01 \x01(\r\x12\x30\n\x05nodes\x18\x02 \x03(\x0b\x32!.rbk.protocol.Message_FallingNodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_fallingdown_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_FALLINGNODE']._serialized_start=43
  _globals['_MESSAGE_FALLINGNODE']._serialized_end=154
  _globals['_MESSAGE_FALLINGDOWN']._serialized_start=156
  _globals['_MESSAGE_FALLINGDOWN']._serialized_end=242
# @@protoc_insertion_point(module_scope)
