# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_recogresult.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_header_pb2 as message__header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19message_recogresult.proto\x12\x0crbk.protocol\x1a\x14message_header.proto\"\x8f\x02\n\x17Message_RecognizeResult\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.rbk.protocol.Message_Header\x12\r\n\x05valid\x18\x02 \x01(\x08\x12\r\n\x05\x63lass\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\t\n\x01x\x18\x05 \x01(\x01\x12\t\n\x01y\x18\x06 \x01(\x01\x12\t\n\x01z\x18\x07 \x01(\x01\x12\n\n\x02qx\x18\x08 \x01(\x01\x12\n\n\x02qy\x18\t \x01(\x01\x12\n\n\x02qz\x18\n \x01(\x01\x12\t\n\x01w\x18\x0b \x01(\x01\x12\x0b\n\x03yaw\x18\x0c \x01(\x01\x12\x11\n\tresultImg\x18\r \x01(\t\x12\x13\n\x0bpalletWidth\x18\x0e \x01(\x01\x12\x15\n\robjectMessage\x18\x0f \x01(\t\"\xe9\x01\n\x1bMessage_RecognizeResultList\x12\x38\n\treco_list\x18\x01 \x03(\x0b\x32%.rbk.protocol.Message_RecognizeResult\x12\x45\n\x0breco_status\x18\x02 \x01(\x0e\x32\x30.rbk.protocol.Message_RecognizeResultList.Status\x12\x0f\n\x07task_id\x18\x03 \x01(\t\"8\n\x06Status\x12\x08\n\x04None\x10\x00\x12\x0b\n\x07Running\x10\x01\x12\n\n\x06\x46\x61iled\x10\x02\x12\x0b\n\x07Success\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_recogresult_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_RECOGNIZERESULT']._serialized_start=66
  _globals['_MESSAGE_RECOGNIZERESULT']._serialized_end=337
  _globals['_MESSAGE_RECOGNIZERESULTLIST']._serialized_start=340
  _globals['_MESSAGE_RECOGNIZERESULTLIST']._serialized_end=573
  _globals['_MESSAGE_RECOGNIZERESULTLIST_STATUS']._serialized_start=517
  _globals['_MESSAGE_RECOGNIZERESULTLIST_STATUS']._serialized_end=573
# @@protoc_insertion_point(module_scope)
