# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_rds_wind_shower_status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$message_rds_wind_shower_status.proto\x12\x10rbk.protocol.rds\"\xbb\x01\n\x18Message_WindShowerStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x19\n\x11\x63onnection_status\x18\x02 \x01(\r\x12\x11\n\tavailable\x18\x03 \x01(\x08\x12\x1a\n\x12wind_shower_status\x18\x04 \x01(\r\x12\x19\n\x11\x65nter_door_status\x18\x05 \x01(\r\x12\x19\n\x11leave_door_status\x18\x06 \x01(\r\x12\x11\n\tforbidden\x18\x07 \x01(\x08\"]\n\x19Message_WindShowersStatus\x12@\n\x0cwind_showers\x18\x01 \x03(\x0b\x32*.rbk.protocol.rds.Message_WindShowerStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_rds_wind_shower_status_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_WINDSHOWERSTATUS']._serialized_start=59
  _globals['_MESSAGE_WINDSHOWERSTATUS']._serialized_end=246
  _globals['_MESSAGE_WINDSHOWERSSTATUS']._serialized_start=248
  _globals['_MESSAGE_WINDSHOWERSSTATUS']._serialized_end=341
# @@protoc_insertion_point(module_scope)
