# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_fork.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12message_fork.proto\x12\x0crbk.protocol\"\x8e\x02\n\x0cMessage_Fork\x12\x0e\n\x06height\x18\x01 \x01(\x01\x12\x0f\n\x07incline\x18\x02 \x01(\x01\x12\x10\n\x08\x66ork_val\x18\x03 \x01(\x01\x12\x13\n\x0bincline_val\x18\x04 \x01(\x01\x12\x12\n\nfork_error\x18\x05 \x01(\x05\x12\x17\n\x0fheight_in_place\x18\x06 \x01(\x08\x12\x18\n\x10incline_in_place\x18\x07 \x01(\x08\x12\x11\n\tget_goods\x18\x08 \x01(\x08\x12\x18\n\x10\x66orward_in_place\x18\t \x01(\x08\x12\x13\n\x0b\x66orward_val\x18\n \x01(\x01\x12\x14\n\x0cpressure_adc\x18\x0b \x01(\x05\x12\x17\n\x0fpressure_actual\x18\x0c \x01(\x01\"\xbd\x02\n\x15Message_Fork_Downward\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0c\n\x04pump\x18\x02 \x01(\x05\x12\x12\n\nencodeline\x18\x03 \x01(\x05\x12\x16\n\x0epressureSensor\x18\x04 \x01(\x05\x12\x11\n\tminHeight\x18\x05 \x01(\x02\x12\x11\n\tmaxHeight\x18\x06 \x01(\x02\x12\x0e\n\x06\x43\x41N_ID\x18\x07 \x01(\x05\x12\x11\n\tmax_angle\x18\x08 \x01(\x02\x12\x11\n\tmin_angle\x18\t \x01(\x02\x12\x14\n\x0c\x64riverPeriod\x18\n \x01(\x02\x12\x10\n\x08upBuffer\x18\x0b \x01(\x02\x12\x12\n\ndownBuffer\x18\x0c \x01(\x02\x12\x16\n\x0eleftSteerRange\x18\r \x01(\x02\x12\x17\n\x0frightSteerRange\x18\x0e \x01(\x02\x12\x13\n\x0bsteeroffset\x18\x0f \x01(\x02\">\n\x12Message_Fork_Speed\x12\x12\n\nmaxUpSpeed\x18\x01 \x01(\x05\x12\x14\n\x0cmaxDownSpeed\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_fork_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_FORK']._serialized_start=37
  _globals['_MESSAGE_FORK']._serialized_end=307
  _globals['_MESSAGE_FORK_DOWNWARD']._serialized_start=310
  _globals['_MESSAGE_FORK_DOWNWARD']._serialized_end=627
  _globals['_MESSAGE_FORK_SPEED']._serialized_start=629
  _globals['_MESSAGE_FORK_SPEED']._serialized_end=691
# @@protoc_insertion_point(module_scope)
