# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_distancesensor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_header_pb2 as message__header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_distancesensor.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cmessage_distancesensor.proto\x12\x0crbk.protocol\x1a\x14message_header.proto\"\x82\x02\n\x14Message_DistanceNode\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.rbk.protocol.Message_Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x0c\n\x04\x64ist\x18\x04 \x01(\x02\x12\r\n\x05valid\x18\x05 \x01(\x08\x12\r\n\x05pos_x\x18\x06 \x01(\x02\x12\r\n\x05pos_y\x18\x07 \x01(\x02\x12\x11\n\tpos_angle\x18\x08 \x01(\x02\x12\x10\n\x08\x61perture\x18\t \x01(\x02\x12\x11\n\tforbidden\x18\n \x01(\x08\x12\x12\n\ncan_router\x18\x0b \x01(\r\x12\r\n\x05rs485\x18\x0c \x01(\r\x12\x0c\n\x04RSSI\x18\r \x01(\r\"J\n\x16Message_DistanceSensor\x12\x30\n\x04node\x18\x01 \x03(\x0b\x32\".rbk.protocol.Message_DistanceNodeb\x06proto3'
  ,
  dependencies=[message__header__pb2.DESCRIPTOR,])




_MESSAGE_DISTANCENODE = _descriptor.Descriptor(
  name='Message_DistanceNode',
  full_name='rbk.protocol.Message_DistanceNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='rbk.protocol.Message_DistanceNode.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='rbk.protocol.Message_DistanceNode.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='rbk.protocol.Message_DistanceNode.id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dist', full_name='rbk.protocol.Message_DistanceNode.dist', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valid', full_name='rbk.protocol.Message_DistanceNode.valid', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos_x', full_name='rbk.protocol.Message_DistanceNode.pos_x', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos_y', full_name='rbk.protocol.Message_DistanceNode.pos_y', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos_angle', full_name='rbk.protocol.Message_DistanceNode.pos_angle', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aperture', full_name='rbk.protocol.Message_DistanceNode.aperture', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='forbidden', full_name='rbk.protocol.Message_DistanceNode.forbidden', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='can_router', full_name='rbk.protocol.Message_DistanceNode.can_router', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rs485', full_name='rbk.protocol.Message_DistanceNode.rs485', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RSSI', full_name='rbk.protocol.Message_DistanceNode.RSSI', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=327,
)


_MESSAGE_DISTANCESENSOR = _descriptor.Descriptor(
  name='Message_DistanceSensor',
  full_name='rbk.protocol.Message_DistanceSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='rbk.protocol.Message_DistanceSensor.node', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=403,
)

_MESSAGE_DISTANCENODE.fields_by_name['header'].message_type = message__header__pb2._MESSAGE_HEADER
_MESSAGE_DISTANCESENSOR.fields_by_name['node'].message_type = _MESSAGE_DISTANCENODE
DESCRIPTOR.message_types_by_name['Message_DistanceNode'] = _MESSAGE_DISTANCENODE
DESCRIPTOR.message_types_by_name['Message_DistanceSensor'] = _MESSAGE_DISTANCESENSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message_DistanceNode = _reflection.GeneratedProtocolMessageType('Message_DistanceNode', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_DISTANCENODE,
  '__module__' : 'message_distancesensor_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_DistanceNode)
  })
_sym_db.RegisterMessage(Message_DistanceNode)

Message_DistanceSensor = _reflection.GeneratedProtocolMessageType('Message_DistanceSensor', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_DISTANCESENSOR,
  '__module__' : 'message_distancesensor_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_DistanceSensor)
  })
_sym_db.RegisterMessage(Message_DistanceSensor)


# @@protoc_insertion_point(module_scope)
