# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_pgvconfig.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_pgvconfig.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17message_pgvconfig.proto\".\n\x12Message_PGV_config\x12\x0b\n\x03id1\x18\x01 \x01(\x05\x12\x0b\n\x03id2\x18\x02 \x01(\x05\x62\x06proto3'
)




_MESSAGE_PGV_CONFIG = _descriptor.Descriptor(
  name='Message_PGV_config',
  full_name='Message_PGV_config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id1', full_name='Message_PGV_config.id1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id2', full_name='Message_PGV_config.id2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['Message_PGV_config'] = _MESSAGE_PGV_CONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message_PGV_config = _reflection.GeneratedProtocolMessageType('Message_PGV_config', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_PGV_CONFIG,
  '__module__' : 'message_pgvconfig_pb2'
  # @@protoc_insertion_point(class_scope:Message_PGV_config)
  })
_sym_db.RegisterMessage(Message_PGV_config)


# @@protoc_insertion_point(module_scope)
