# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_rds_robots_cmds.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_header_pb2 as message__header__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_rds_robots_cmds.proto',
  package='rbk.protocol.rds',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dmessage_rds_robots_cmds.proto\x12\x10rbk.protocol.rds\x1a\x14message_header.proto\x1a\x1egoogle/protobuf/wrappers.proto\"W\n\x10Message_RobotCMD\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x0c\n\x04\x63ode\x18\x03 \x01(\r\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0b\n\x03\x63md\x18\x05 \x01(\t\"v\n\x0eMessage_RDSCMD\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.rbk.protocol.Message_Header\x12\x36\n\nrobot_cmds\x18\x02 \x03(\x0b\x32\".rbk.protocol.rds.Message_RobotCMDb\x06proto3'
  ,
  dependencies=[message__header__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_MESSAGE_ROBOTCMD = _descriptor.Descriptor(
  name='Message_RobotCMD',
  full_name='rbk.protocol.rds.Message_RobotCMD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='rbk.protocol.rds.Message_RobotCMD.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='rbk.protocol.rds.Message_RobotCMD.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='rbk.protocol.rds.Message_RobotCMD.code', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='rbk.protocol.rds.Message_RobotCMD.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cmd', full_name='rbk.protocol.rds.Message_RobotCMD.cmd', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=192,
)


_MESSAGE_RDSCMD = _descriptor.Descriptor(
  name='Message_RDSCMD',
  full_name='rbk.protocol.rds.Message_RDSCMD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='rbk.protocol.rds.Message_RDSCMD.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='robot_cmds', full_name='rbk.protocol.rds.Message_RDSCMD.robot_cmds', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=312,
)

_MESSAGE_RDSCMD.fields_by_name['header'].message_type = message__header__pb2._MESSAGE_HEADER
_MESSAGE_RDSCMD.fields_by_name['robot_cmds'].message_type = _MESSAGE_ROBOTCMD
DESCRIPTOR.message_types_by_name['Message_RobotCMD'] = _MESSAGE_ROBOTCMD
DESCRIPTOR.message_types_by_name['Message_RDSCMD'] = _MESSAGE_RDSCMD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message_RobotCMD = _reflection.GeneratedProtocolMessageType('Message_RobotCMD', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_ROBOTCMD,
  '__module__' : 'message_rds_robots_cmds_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.rds.Message_RobotCMD)
  })
_sym_db.RegisterMessage(Message_RobotCMD)

Message_RDSCMD = _reflection.GeneratedProtocolMessageType('Message_RDSCMD', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_RDSCMD,
  '__module__' : 'message_rds_robots_cmds_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.rds.Message_RDSCMD)
  })
_sym_db.RegisterMessage(Message_RDSCMD)


# @@protoc_insertion_point(module_scope)
