# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_407Param.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_407Param.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16message_407Param.proto\x12\x0crbk.protocol\"\x8e\x01\n\x0eMessage_407map\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\nbool_value\x18\x02 \x01(\x08H\x00\x12\x15\n\x0bint32_value\x18\x03 \x01(\x05H\x00\x12\x16\n\x0cuint32_value\x18\x04 \x01(\rH\x00\x12\x16\n\x0c\x64ouble_value\x18\x05 \x01(\x01H\x00\x42\x12\n\x10oneof_paramValue\"D\n\x10Message_407Param\x12\x30\n\nparam_maps\x18\x01 \x03(\x0b\x32\x1c.rbk.protocol.Message_407mapb\x06proto3'
)




_MESSAGE_407MAP = _descriptor.Descriptor(
  name='Message_407map',
  full_name='rbk.protocol.Message_407map',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='rbk.protocol.Message_407map.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bool_value', full_name='rbk.protocol.Message_407map.bool_value', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int32_value', full_name='rbk.protocol.Message_407map.int32_value', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uint32_value', full_name='rbk.protocol.Message_407map.uint32_value', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='double_value', full_name='rbk.protocol.Message_407map.double_value', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='oneof_paramValue', full_name='rbk.protocol.Message_407map.oneof_paramValue',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=41,
  serialized_end=183,
)


_MESSAGE_407PARAM = _descriptor.Descriptor(
  name='Message_407Param',
  full_name='rbk.protocol.Message_407Param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='param_maps', full_name='rbk.protocol.Message_407Param.param_maps', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=253,
)

_MESSAGE_407MAP.oneofs_by_name['oneof_paramValue'].fields.append(
  _MESSAGE_407MAP.fields_by_name['bool_value'])
_MESSAGE_407MAP.fields_by_name['bool_value'].containing_oneof = _MESSAGE_407MAP.oneofs_by_name['oneof_paramValue']
_MESSAGE_407MAP.oneofs_by_name['oneof_paramValue'].fields.append(
  _MESSAGE_407MAP.fields_by_name['int32_value'])
_MESSAGE_407MAP.fields_by_name['int32_value'].containing_oneof = _MESSAGE_407MAP.oneofs_by_name['oneof_paramValue']
_MESSAGE_407MAP.oneofs_by_name['oneof_paramValue'].fields.append(
  _MESSAGE_407MAP.fields_by_name['uint32_value'])
_MESSAGE_407MAP.fields_by_name['uint32_value'].containing_oneof = _MESSAGE_407MAP.oneofs_by_name['oneof_paramValue']
_MESSAGE_407MAP.oneofs_by_name['oneof_paramValue'].fields.append(
  _MESSAGE_407MAP.fields_by_name['double_value'])
_MESSAGE_407MAP.fields_by_name['double_value'].containing_oneof = _MESSAGE_407MAP.oneofs_by_name['oneof_paramValue']
_MESSAGE_407PARAM.fields_by_name['param_maps'].message_type = _MESSAGE_407MAP
DESCRIPTOR.message_types_by_name['Message_407map'] = _MESSAGE_407MAP
DESCRIPTOR.message_types_by_name['Message_407Param'] = _MESSAGE_407PARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message_407map = _reflection.GeneratedProtocolMessageType('Message_407map', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_407MAP,
  '__module__' : 'message_407Param_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_407map)
  })
_sym_db.RegisterMessage(Message_407map)

Message_407Param = _reflection.GeneratedProtocolMessageType('Message_407Param', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_407PARAM,
  '__module__' : 'message_407Param_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_407Param)
  })
_sym_db.RegisterMessage(Message_407Param)


# @@protoc_insertion_point(module_scope)
