# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_roller.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_roller.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14message_roller.proto\x12\x0crbk.protocol\"|\n\x0eMessage_Roller\x12\x0c\n\x04mode\x18\x01 \x01(\x08\x12\r\n\x05state\x18\x02 \x01(\r\x12\x0e\n\x06\x65nable\x18\x03 \x01(\x08\x12\x11\n\terrorCode\x18\x04 \x01(\r\x12\x0e\n\x06isFull\x18\x05 \x01(\x08\x12\r\n\x05speed\x18\x06 \x01(\r\x12\x0b\n\x03\x65mc\x18\x07 \x01(\x08\"\"\n\x12Message_Peripheral\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\rb\x06proto3'
)




_MESSAGE_ROLLER = _descriptor.Descriptor(
  name='Message_Roller',
  full_name='rbk.protocol.Message_Roller',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='rbk.protocol.Message_Roller.mode', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='rbk.protocol.Message_Roller.state', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enable', full_name='rbk.protocol.Message_Roller.enable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='rbk.protocol.Message_Roller.errorCode', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isFull', full_name='rbk.protocol.Message_Roller.isFull', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='rbk.protocol.Message_Roller.speed', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='emc', full_name='rbk.protocol.Message_Roller.emc', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=162,
)


_MESSAGE_PERIPHERAL = _descriptor.Descriptor(
  name='Message_Peripheral',
  full_name='rbk.protocol.Message_Peripheral',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='rbk.protocol.Message_Peripheral.data', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=198,
)

DESCRIPTOR.message_types_by_name['Message_Roller'] = _MESSAGE_ROLLER
DESCRIPTOR.message_types_by_name['Message_Peripheral'] = _MESSAGE_PERIPHERAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message_Roller = _reflection.GeneratedProtocolMessageType('Message_Roller', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_ROLLER,
  '__module__' : 'message_roller_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_Roller)
  })
_sym_db.RegisterMessage(Message_Roller)

Message_Peripheral = _reflection.GeneratedProtocolMessageType('Message_Peripheral', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_PERIPHERAL,
  '__module__' : 'message_roller_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_Peripheral)
  })
_sym_db.RegisterMessage(Message_Peripheral)


# @@protoc_insertion_point(module_scope)
