# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_pgv.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_header_pb2 as message__header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_pgv.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11message_pgv.proto\x12\x0crbk.protocol\x1a\x14message_header.proto\"\xc7\x01\n\x10Message_PGV_Info\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\x0b\n\x03yaw\x18\x04 \x01(\x01\x12\x0c\n\x04\x66unc\x18\x05 \x01(\t\x12\x12\n\ncoordinate\x18\x06 \x01(\t\x12\r\n\x05xunit\x18\x07 \x01(\x01\x12\r\n\x05yunit\x18\x08 \x01(\x01\x12\x12\n\nangle_unit\x18\t \x01(\x01\x12\x11\n\tis_upside\x18\n \x01(\x08\x12\x0e\n\x06xrange\x18\x0b \x01(\x01\x12\x0e\n\x06yrange\x18\x0c \x01(\x01\"\xb4\x02\n\x0fMessage_PGV_DMT\x12\x12\n\ntag_diff_x\x18\x01 \x01(\x01\x12\x12\n\ntag_diff_y\x18\x02 \x01(\x01\x12\x16\n\x0etag_diff_angle\x18\x03 \x01(\x01\x12\x11\n\ttag_value\x18\x04 \x01(\r\x12\x14\n\x0cwarning_code\x18\x05 \x01(\r\x12\x16\n\x0e\x64\x65vice_address\x18\x06 \x01(\r\x12\x17\n\x0fis_DMT_detected\x18\x07 \x01(\x08\x12\x12\n\nerror_code\x18\x08 \x01(\r\x12,\n\x06header\x18\t \x01(\x0b\x32\x1c.rbk.protocol.Message_Header\x12\x30\n\x08pgv_info\x18\n \x01(\x0b\x32\x1e.rbk.protocol.Message_PGV_Info\x12\x13\n\x0bis_bar_code\x18\x0b \x01(\x08\"\xac\x01\n\x14Message_Tag_position\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.rbk.protocol.Message_Header\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\r\n\x05\x61ngle\x18\x04 \x01(\x01\x12\x11\n\ttag_value\x18\x05 \x01(\r\x12\x17\n\x0fis_DMT_detected\x18\x06 \x01(\x08\x12\x15\n\ris_in_QR_area\x18\x07 \x01(\x08\":\n\x0bMessage_PGV\x12+\n\x04pgvs\x18\x01 \x03(\x0b\x32\x1d.rbk.protocol.Message_PGV_DMTb\x06proto3'
  ,
  dependencies=[message__header__pb2.DESCRIPTOR,])




_MESSAGE_PGV_INFO = _descriptor.Descriptor(
  name='Message_PGV_Info',
  full_name='rbk.protocol.Message_PGV_Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='rbk.protocol.Message_PGV_Info.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='rbk.protocol.Message_PGV_Info.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='rbk.protocol.Message_PGV_Info.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='rbk.protocol.Message_PGV_Info.yaw', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='func', full_name='rbk.protocol.Message_PGV_Info.func', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='coordinate', full_name='rbk.protocol.Message_PGV_Info.coordinate', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xunit', full_name='rbk.protocol.Message_PGV_Info.xunit', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yunit', full_name='rbk.protocol.Message_PGV_Info.yunit', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angle_unit', full_name='rbk.protocol.Message_PGV_Info.angle_unit', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_upside', full_name='rbk.protocol.Message_PGV_Info.is_upside', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xrange', full_name='rbk.protocol.Message_PGV_Info.xrange', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yrange', full_name='rbk.protocol.Message_PGV_Info.yrange', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=257,
)


_MESSAGE_PGV_DMT = _descriptor.Descriptor(
  name='Message_PGV_DMT',
  full_name='rbk.protocol.Message_PGV_DMT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag_diff_x', full_name='rbk.protocol.Message_PGV_DMT.tag_diff_x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tag_diff_y', full_name='rbk.protocol.Message_PGV_DMT.tag_diff_y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tag_diff_angle', full_name='rbk.protocol.Message_PGV_DMT.tag_diff_angle', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tag_value', full_name='rbk.protocol.Message_PGV_DMT.tag_value', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='warning_code', full_name='rbk.protocol.Message_PGV_DMT.warning_code', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_address', full_name='rbk.protocol.Message_PGV_DMT.device_address', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_DMT_detected', full_name='rbk.protocol.Message_PGV_DMT.is_DMT_detected', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='rbk.protocol.Message_PGV_DMT.error_code', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='header', full_name='rbk.protocol.Message_PGV_DMT.header', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pgv_info', full_name='rbk.protocol.Message_PGV_DMT.pgv_info', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_bar_code', full_name='rbk.protocol.Message_PGV_DMT.is_bar_code', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=568,
)


_MESSAGE_TAG_POSITION = _descriptor.Descriptor(
  name='Message_Tag_position',
  full_name='rbk.protocol.Message_Tag_position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='rbk.protocol.Message_Tag_position.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='rbk.protocol.Message_Tag_position.x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='rbk.protocol.Message_Tag_position.y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angle', full_name='rbk.protocol.Message_Tag_position.angle', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tag_value', full_name='rbk.protocol.Message_Tag_position.tag_value', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_DMT_detected', full_name='rbk.protocol.Message_Tag_position.is_DMT_detected', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_in_QR_area', full_name='rbk.protocol.Message_Tag_position.is_in_QR_area', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=571,
  serialized_end=743,
)


_MESSAGE_PGV = _descriptor.Descriptor(
  name='Message_PGV',
  full_name='rbk.protocol.Message_PGV',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pgvs', full_name='rbk.protocol.Message_PGV.pgvs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=745,
  serialized_end=803,
)

_MESSAGE_PGV_DMT.fields_by_name['header'].message_type = message__header__pb2._MESSAGE_HEADER
_MESSAGE_PGV_DMT.fields_by_name['pgv_info'].message_type = _MESSAGE_PGV_INFO
_MESSAGE_TAG_POSITION.fields_by_name['header'].message_type = message__header__pb2._MESSAGE_HEADER
_MESSAGE_PGV.fields_by_name['pgvs'].message_type = _MESSAGE_PGV_DMT
DESCRIPTOR.message_types_by_name['Message_PGV_Info'] = _MESSAGE_PGV_INFO
DESCRIPTOR.message_types_by_name['Message_PGV_DMT'] = _MESSAGE_PGV_DMT
DESCRIPTOR.message_types_by_name['Message_Tag_position'] = _MESSAGE_TAG_POSITION
DESCRIPTOR.message_types_by_name['Message_PGV'] = _MESSAGE_PGV
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message_PGV_Info = _reflection.GeneratedProtocolMessageType('Message_PGV_Info', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_PGV_INFO,
  '__module__' : 'message_pgv_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_PGV_Info)
  })
_sym_db.RegisterMessage(Message_PGV_Info)

Message_PGV_DMT = _reflection.GeneratedProtocolMessageType('Message_PGV_DMT', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_PGV_DMT,
  '__module__' : 'message_pgv_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_PGV_DMT)
  })
_sym_db.RegisterMessage(Message_PGV_DMT)

Message_Tag_position = _reflection.GeneratedProtocolMessageType('Message_Tag_position', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_TAG_POSITION,
  '__module__' : 'message_pgv_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_Tag_position)
  })
_sym_db.RegisterMessage(Message_Tag_position)

Message_PGV = _reflection.GeneratedProtocolMessageType('Message_PGV', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_PGV,
  '__module__' : 'message_pgv_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_PGV)
  })
_sym_db.RegisterMessage(Message_PGV)


# @@protoc_insertion_point(module_scope)
