# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_recogresult.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_header_pb2 as message__header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_recogresult.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19message_recogresult.proto\x12\x0crbk.protocol\x1a\x14message_header.proto\"\x8f\x02\n\x17Message_RecognizeResult\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.rbk.protocol.Message_Header\x12\r\n\x05valid\x18\x02 \x01(\x08\x12\r\n\x05\x63lass\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\t\n\x01x\x18\x05 \x01(\x01\x12\t\n\x01y\x18\x06 \x01(\x01\x12\t\n\x01z\x18\x07 \x01(\x01\x12\n\n\x02qx\x18\x08 \x01(\x01\x12\n\n\x02qy\x18\t \x01(\x01\x12\n\n\x02qz\x18\n \x01(\x01\x12\t\n\x01w\x18\x0b \x01(\x01\x12\x0b\n\x03yaw\x18\x0c \x01(\x01\x12\x11\n\tresultImg\x18\r \x01(\t\x12\x13\n\x0bpalletWidth\x18\x0e \x01(\x01\x12\x15\n\robjectMessage\x18\x0f \x01(\t\"\xe9\x01\n\x1bMessage_RecognizeResultList\x12\x38\n\treco_list\x18\x01 \x03(\x0b\x32%.rbk.protocol.Message_RecognizeResult\x12\x45\n\x0breco_status\x18\x02 \x01(\x0e\x32\x30.rbk.protocol.Message_RecognizeResultList.Status\x12\x0f\n\x07task_id\x18\x03 \x01(\t\"8\n\x06Status\x12\x08\n\x04None\x10\x00\x12\x0b\n\x07Running\x10\x01\x12\n\n\x06\x46\x61iled\x10\x02\x12\x0b\n\x07Success\x10\x03\x62\x06proto3'
  ,
  dependencies=[message__header__pb2.DESCRIPTOR,])



_MESSAGE_RECOGNIZERESULTLIST_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='rbk.protocol.Message_RecognizeResultList.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Running', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Failed', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Success', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=517,
  serialized_end=573,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_RECOGNIZERESULTLIST_STATUS)


_MESSAGE_RECOGNIZERESULT = _descriptor.Descriptor(
  name='Message_RecognizeResult',
  full_name='rbk.protocol.Message_RecognizeResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='rbk.protocol.Message_RecognizeResult.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valid', full_name='rbk.protocol.Message_RecognizeResult.valid', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='class', full_name='rbk.protocol.Message_RecognizeResult.class', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='rbk.protocol.Message_RecognizeResult.type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='rbk.protocol.Message_RecognizeResult.x', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='rbk.protocol.Message_RecognizeResult.y', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='rbk.protocol.Message_RecognizeResult.z', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qx', full_name='rbk.protocol.Message_RecognizeResult.qx', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qy', full_name='rbk.protocol.Message_RecognizeResult.qy', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qz', full_name='rbk.protocol.Message_RecognizeResult.qz', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='w', full_name='rbk.protocol.Message_RecognizeResult.w', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='rbk.protocol.Message_RecognizeResult.yaw', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resultImg', full_name='rbk.protocol.Message_RecognizeResult.resultImg', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='palletWidth', full_name='rbk.protocol.Message_RecognizeResult.palletWidth', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='objectMessage', full_name='rbk.protocol.Message_RecognizeResult.objectMessage', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=337,
)


_MESSAGE_RECOGNIZERESULTLIST = _descriptor.Descriptor(
  name='Message_RecognizeResultList',
  full_name='rbk.protocol.Message_RecognizeResultList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reco_list', full_name='rbk.protocol.Message_RecognizeResultList.reco_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reco_status', full_name='rbk.protocol.Message_RecognizeResultList.reco_status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='rbk.protocol.Message_RecognizeResultList.task_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MESSAGE_RECOGNIZERESULTLIST_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=573,
)

_MESSAGE_RECOGNIZERESULT.fields_by_name['header'].message_type = message__header__pb2._MESSAGE_HEADER
_MESSAGE_RECOGNIZERESULTLIST.fields_by_name['reco_list'].message_type = _MESSAGE_RECOGNIZERESULT
_MESSAGE_RECOGNIZERESULTLIST.fields_by_name['reco_status'].enum_type = _MESSAGE_RECOGNIZERESULTLIST_STATUS
_MESSAGE_RECOGNIZERESULTLIST_STATUS.containing_type = _MESSAGE_RECOGNIZERESULTLIST
DESCRIPTOR.message_types_by_name['Message_RecognizeResult'] = _MESSAGE_RECOGNIZERESULT
DESCRIPTOR.message_types_by_name['Message_RecognizeResultList'] = _MESSAGE_RECOGNIZERESULTLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message_RecognizeResult = _reflection.GeneratedProtocolMessageType('Message_RecognizeResult', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_RECOGNIZERESULT,
  '__module__' : 'message_recogresult_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_RecognizeResult)
  })
_sym_db.RegisterMessage(Message_RecognizeResult)

Message_RecognizeResultList = _reflection.GeneratedProtocolMessageType('Message_RecognizeResultList', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_RECOGNIZERESULTLIST,
  '__module__' : 'message_recogresult_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_RecognizeResultList)
  })
_sym_db.RegisterMessage(Message_RecognizeResultList)


# @@protoc_insertion_point(module_scope)
