# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_liftconfig.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_liftconfig.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18message_liftconfig.proto\x12\x0crbk.protocol\"\x8b\x03\n\x16Message_Lift_Elevation\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x13\n\x0b\x64riverBrand\x18\x02 \x01(\x05\x12\x0f\n\x07Inverse\x18\x03 \x01(\x08\x12\x13\n\x0bhaveEncoder\x18\x04 \x01(\x08\x12\x18\n\x10\x65ncoderWithMotor\x18\x05 \x01(\x08\x12\x14\n\x0c\x65ncoderLines\x18\x06 \x01(\x05\x12\x12\n\nmmCntRatio\x18\x07 \x01(\x02\x12\x11\n\tlimitType\x18\x08 \x01(\x05\x12\x10\n\x08toplimit\x18\t \x01(\x02\x12\x13\n\x0b\x62ottomlimit\x18\n \x01(\x02\x12\x18\n\x10topDIHighTrigger\x18\x0b \x01(\x08\x12\x1b\n\x13\x62ottomDIHighTrigger\x18\x0c \x01(\x08\x12\x17\n\x0fsafeControlType\x18\r \x01(\x05\x12\x11\n\ttimeLimit\x18\x0e \x01(\x05\x12\x18\n\x10setSpeedPriority\x18\x0f \x01(\x05\x12\x1a\n\x12setToLimitPriority\x18\x10 \x01(\x05\x12\x13\n\x0bheightLimit\x18\x11 \x01(\x05\"\x9f\x03\n\x15Message_Lift_Rotation\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x13\n\x0b\x64riverBrand\x18\x02 \x01(\x05\x12\x0f\n\x07Inverse\x18\x03 \x01(\x08\x12\x13\n\x0bhaveEncoder\x18\x04 \x01(\x08\x12\x18\n\x10\x65ncoderWithMotor\x18\x05 \x01(\x08\x12\x14\n\x0c\x65ncoderLines\x18\x06 \x01(\x05\x12\x13\n\x0b\x64\x65greeRatio\x18\x07 \x01(\x02\x12\x18\n\x10setSpeedPriority\x18\x08 \x01(\x05\x12\x1a\n\x12spinDegreePriority\x18\t \x01(\x05\x12\x17\n\x0fspinDegreeSpeed\x18\n \x01(\x02\x12 \n\x18spinDegreeFollowPriority\x18\x0b \x01(\x05\x12 \n\x18spinDegreeFollowWithZero\x18\x0c \x01(\x08\x12\x13\n\x0bzeroPointDI\x18\r \x01(\x05\x12\x15\n\rDIHighTrigger\x18\x0e \x01(\x08\x12\x1f\n\x17spinFollowZeroInitSpeed\x18\x0f \x01(\x02\x12\x1a\n\x12spinDegreeWithZero\x18\x10 \x01(\x08\x62\x06proto3'
)




_MESSAGE_LIFT_ELEVATION = _descriptor.Descriptor(
  name='Message_Lift_Elevation',
  full_name='rbk.protocol.Message_Lift_Elevation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='rbk.protocol.Message_Lift_Elevation.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='driverBrand', full_name='rbk.protocol.Message_Lift_Elevation.driverBrand', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Inverse', full_name='rbk.protocol.Message_Lift_Elevation.Inverse', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='haveEncoder', full_name='rbk.protocol.Message_Lift_Elevation.haveEncoder', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encoderWithMotor', full_name='rbk.protocol.Message_Lift_Elevation.encoderWithMotor', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encoderLines', full_name='rbk.protocol.Message_Lift_Elevation.encoderLines', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mmCntRatio', full_name='rbk.protocol.Message_Lift_Elevation.mmCntRatio', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limitType', full_name='rbk.protocol.Message_Lift_Elevation.limitType', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='toplimit', full_name='rbk.protocol.Message_Lift_Elevation.toplimit', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bottomlimit', full_name='rbk.protocol.Message_Lift_Elevation.bottomlimit', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topDIHighTrigger', full_name='rbk.protocol.Message_Lift_Elevation.topDIHighTrigger', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bottomDIHighTrigger', full_name='rbk.protocol.Message_Lift_Elevation.bottomDIHighTrigger', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='safeControlType', full_name='rbk.protocol.Message_Lift_Elevation.safeControlType', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeLimit', full_name='rbk.protocol.Message_Lift_Elevation.timeLimit', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='setSpeedPriority', full_name='rbk.protocol.Message_Lift_Elevation.setSpeedPriority', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='setToLimitPriority', full_name='rbk.protocol.Message_Lift_Elevation.setToLimitPriority', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heightLimit', full_name='rbk.protocol.Message_Lift_Elevation.heightLimit', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=438,
)


_MESSAGE_LIFT_ROTATION = _descriptor.Descriptor(
  name='Message_Lift_Rotation',
  full_name='rbk.protocol.Message_Lift_Rotation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='rbk.protocol.Message_Lift_Rotation.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='driverBrand', full_name='rbk.protocol.Message_Lift_Rotation.driverBrand', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Inverse', full_name='rbk.protocol.Message_Lift_Rotation.Inverse', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='haveEncoder', full_name='rbk.protocol.Message_Lift_Rotation.haveEncoder', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encoderWithMotor', full_name='rbk.protocol.Message_Lift_Rotation.encoderWithMotor', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encoderLines', full_name='rbk.protocol.Message_Lift_Rotation.encoderLines', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='degreeRatio', full_name='rbk.protocol.Message_Lift_Rotation.degreeRatio', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='setSpeedPriority', full_name='rbk.protocol.Message_Lift_Rotation.setSpeedPriority', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spinDegreePriority', full_name='rbk.protocol.Message_Lift_Rotation.spinDegreePriority', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spinDegreeSpeed', full_name='rbk.protocol.Message_Lift_Rotation.spinDegreeSpeed', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spinDegreeFollowPriority', full_name='rbk.protocol.Message_Lift_Rotation.spinDegreeFollowPriority', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spinDegreeFollowWithZero', full_name='rbk.protocol.Message_Lift_Rotation.spinDegreeFollowWithZero', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='zeroPointDI', full_name='rbk.protocol.Message_Lift_Rotation.zeroPointDI', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='DIHighTrigger', full_name='rbk.protocol.Message_Lift_Rotation.DIHighTrigger', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spinFollowZeroInitSpeed', full_name='rbk.protocol.Message_Lift_Rotation.spinFollowZeroInitSpeed', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spinDegreeWithZero', full_name='rbk.protocol.Message_Lift_Rotation.spinDegreeWithZero', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=856,
)

DESCRIPTOR.message_types_by_name['Message_Lift_Elevation'] = _MESSAGE_LIFT_ELEVATION
DESCRIPTOR.message_types_by_name['Message_Lift_Rotation'] = _MESSAGE_LIFT_ROTATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message_Lift_Elevation = _reflection.GeneratedProtocolMessageType('Message_Lift_Elevation', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_LIFT_ELEVATION,
  '__module__' : 'message_liftconfig_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_Lift_Elevation)
  })
_sym_db.RegisterMessage(Message_Lift_Elevation)

Message_Lift_Rotation = _reflection.GeneratedProtocolMessageType('Message_Lift_Rotation', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_LIFT_ROTATION,
  '__module__' : 'message_liftconfig_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_Lift_Rotation)
  })
_sym_db.RegisterMessage(Message_Lift_Rotation)


# @@protoc_insertion_point(module_scope)
