# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_rpc.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11message_rpc.proto\x12\x0crbk.protocol\"\x8f\x02\n\x10Message_RPCValue\x12\x36\n\x04type\x18\x01 \x01(\x0e\x32(.rbk.protocol.Message_RPCValue.ValueType\x12\x14\n\x0cvalue_string\x18\x02 \x01(\t\x12\x14\n\x0cvalue_number\x18\x03 \x01(\x01\x12\x16\n\x0evalue_function\x18\x04 \x01(\t\x12\x12\n\nvalue_bool\x18\x05 \x01(\x08\"k\n\tValueType\x12\x0c\n\x08NullType\x10\x00\x12\n\n\x06Number\x10\x01\x12\n\n\x06String\x10\x02\x12\t\n\x05Table\x10\x03\x12\x07\n\x03Nil\x10\x04\x12\x08\n\x04\x42ool\x10\x05\x12\x0c\n\x08\x46unction\x10\x06\x12\x0c\n\x08Userdata\x10\x07\"y\n\x11Message_RPCRequst\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tfunc_name\x18\x02 \x01(\t\x12.\n\x06params\x18\x03 \x03(\x0b\x32\x1e.rbk.protocol.Message_RPCValue\x12\x15\n\rneed_response\x18\x04 \x01(\x08\"^\n\x13Message_RPCResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12,\n\x04rets\x18\x02 \x03(\x0b\x32\x1e.rbk.protocol.Message_RPCValue\x12\r\n\x05is_ok\x18\x03 \x01(\x08\x62\x06proto3'
)



_MESSAGE_RPCVALUE_VALUETYPE = _descriptor.EnumDescriptor(
  name='ValueType',
  full_name='rbk.protocol.Message_RPCValue.ValueType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NullType', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Number', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='String', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Table', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Nil', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Bool', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Function', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Userdata', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=200,
  serialized_end=307,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_RPCVALUE_VALUETYPE)


_MESSAGE_RPCVALUE = _descriptor.Descriptor(
  name='Message_RPCValue',
  full_name='rbk.protocol.Message_RPCValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='rbk.protocol.Message_RPCValue.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_string', full_name='rbk.protocol.Message_RPCValue.value_string', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_number', full_name='rbk.protocol.Message_RPCValue.value_number', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_function', full_name='rbk.protocol.Message_RPCValue.value_function', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_bool', full_name='rbk.protocol.Message_RPCValue.value_bool', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MESSAGE_RPCVALUE_VALUETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=307,
)


_MESSAGE_RPCREQUST = _descriptor.Descriptor(
  name='Message_RPCRequst',
  full_name='rbk.protocol.Message_RPCRequst',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rbk.protocol.Message_RPCRequst.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='func_name', full_name='rbk.protocol.Message_RPCRequst.func_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='rbk.protocol.Message_RPCRequst.params', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='need_response', full_name='rbk.protocol.Message_RPCRequst.need_response', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=430,
)


_MESSAGE_RPCRESPONSE = _descriptor.Descriptor(
  name='Message_RPCResponse',
  full_name='rbk.protocol.Message_RPCResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rbk.protocol.Message_RPCResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rets', full_name='rbk.protocol.Message_RPCResponse.rets', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_ok', full_name='rbk.protocol.Message_RPCResponse.is_ok', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=526,
)

_MESSAGE_RPCVALUE.fields_by_name['type'].enum_type = _MESSAGE_RPCVALUE_VALUETYPE
_MESSAGE_RPCVALUE_VALUETYPE.containing_type = _MESSAGE_RPCVALUE
_MESSAGE_RPCREQUST.fields_by_name['params'].message_type = _MESSAGE_RPCVALUE
_MESSAGE_RPCRESPONSE.fields_by_name['rets'].message_type = _MESSAGE_RPCVALUE
DESCRIPTOR.message_types_by_name['Message_RPCValue'] = _MESSAGE_RPCVALUE
DESCRIPTOR.message_types_by_name['Message_RPCRequst'] = _MESSAGE_RPCREQUST
DESCRIPTOR.message_types_by_name['Message_RPCResponse'] = _MESSAGE_RPCRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message_RPCValue = _reflection.GeneratedProtocolMessageType('Message_RPCValue', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_RPCVALUE,
  '__module__' : 'message_rpc_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_RPCValue)
  })
_sym_db.RegisterMessage(Message_RPCValue)

Message_RPCRequst = _reflection.GeneratedProtocolMessageType('Message_RPCRequst', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_RPCREQUST,
  '__module__' : 'message_rpc_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_RPCRequst)
  })
_sym_db.RegisterMessage(Message_RPCRequst)

Message_RPCResponse = _reflection.GeneratedProtocolMessageType('Message_RPCResponse', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_RPCRESPONSE,
  '__module__' : 'message_rpc_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_RPCResponse)
  })
_sym_db.RegisterMessage(Message_RPCResponse)


# @@protoc_insertion_point(module_scope)
