# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_tcs_comm_v2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_tcs_comm_v2.proto',
  package='route.v2',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19message_tcs_comm_v2.proto\x12\x08route.v2\"E\n\x16Message_Command_Normal\x12+\n\x08\x63ommands\x18\x01 \x03(\x0b\x32\x19.route.v2.Message_Command\"\x9e\x01\n\x0fMessage_Command\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04step\x18\x02 \x01(\t\x12\x11\n\toperation\x18\x03 \x01(\t\x12\x17\n\x0fisFinalMovement\x18\x04 \x01(\x08\x12\x30\n\nproperties\x18\x05 \x03(\x0b\x32\x1c.route.v2.Message_Properties\x12\x13\n\x0bsourcePoint\x18\x06 \x01(\t\"]\n\x18Message_Command_Advanced\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x30\n\nproperties\x18\x02 \x03(\x0b\x32\x1c.route.v2.Message_Properties\"\xdc\x03\n\x17Message_Response_Status\x12=\n\x05state\x18\x01 \x01(\x0e\x32..route.v2.Message_Response_Status.VehicleState\x12I\n\x08\x65xeState\x18\x02 \x01(\x0e\x32\x37.route.v2.Message_Response_Status.VehicleExecutingState\x12\x10\n\x08position\x18\x03 \x01(\t\x12\x13\n\x0b\x65nergyLevel\x18\x04 \x01(\r\x12\x41\n\x13loadHandlingDevices\x18\x05 \x03(\x0b\x32$.route.v2.Message_LoadHandlingDevice\x12/\n\nerrorInfos\x18\x06 \x03(\x0b\x32\x1b.route.v2.Message_Rbk_Error\"^\n\x0cVehicleState\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0bUNAVAILABLE\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\x08\n\x04IDLE\x10\x03\x12\r\n\tEXECUTING\x10\x04\x12\x0c\n\x08\x43HARGING\x10\x05\"<\n\x15VehicleExecutingState\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06MOVING\x10\x01\x12\r\n\tOPERATING\x10\x02\"U\n\x11Message_Rbk_Error\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"4\n\x1dMessage_Response_Confirmation\x12\x13\n\x0b\x63ommandsNum\x18\x01 \x01(\r\"0\n\x12Message_Properties\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"9\n\x1aMessage_LoadHandlingDevice\x12\r\n\x05label\x18\x01 \x01(\t\x12\x0c\n\x04\x66ull\x18\x02 \x01(\x08\x62\x06proto3'
)



_MESSAGE_RESPONSE_STATUS_VEHICLESTATE = _descriptor.EnumDescriptor(
  name='VehicleState',
  full_name='route.v2.Message_Response_Status.VehicleState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNAVAILABLE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EXECUTING', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHARGING', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=687,
  serialized_end=781,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_RESPONSE_STATUS_VEHICLESTATE)

_MESSAGE_RESPONSE_STATUS_VEHICLEEXECUTINGSTATE = _descriptor.EnumDescriptor(
  name='VehicleExecutingState',
  full_name='route.v2.Message_Response_Status.VehicleExecutingState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOVING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OPERATING', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=783,
  serialized_end=843,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_RESPONSE_STATUS_VEHICLEEXECUTINGSTATE)


_MESSAGE_COMMAND_NORMAL = _descriptor.Descriptor(
  name='Message_Command_Normal',
  full_name='route.v2.Message_Command_Normal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='commands', full_name='route.v2.Message_Command_Normal.commands', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=108,
)


_MESSAGE_COMMAND = _descriptor.Descriptor(
  name='Message_Command',
  full_name='route.v2.Message_Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='route.v2.Message_Command.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='step', full_name='route.v2.Message_Command.step', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation', full_name='route.v2.Message_Command.operation', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isFinalMovement', full_name='route.v2.Message_Command.isFinalMovement', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='properties', full_name='route.v2.Message_Command.properties', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sourcePoint', full_name='route.v2.Message_Command.sourcePoint', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=269,
)


_MESSAGE_COMMAND_ADVANCED = _descriptor.Descriptor(
  name='Message_Command_Advanced',
  full_name='route.v2.Message_Command_Advanced',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='route.v2.Message_Command_Advanced.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='properties', full_name='route.v2.Message_Command_Advanced.properties', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=364,
)


_MESSAGE_RESPONSE_STATUS = _descriptor.Descriptor(
  name='Message_Response_Status',
  full_name='route.v2.Message_Response_Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='route.v2.Message_Response_Status.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exeState', full_name='route.v2.Message_Response_Status.exeState', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='route.v2.Message_Response_Status.position', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='energyLevel', full_name='route.v2.Message_Response_Status.energyLevel', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loadHandlingDevices', full_name='route.v2.Message_Response_Status.loadHandlingDevices', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errorInfos', full_name='route.v2.Message_Response_Status.errorInfos', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MESSAGE_RESPONSE_STATUS_VEHICLESTATE,
    _MESSAGE_RESPONSE_STATUS_VEHICLEEXECUTINGSTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=843,
)


_MESSAGE_RBK_ERROR = _descriptor.Descriptor(
  name='Message_Rbk_Error',
  full_name='route.v2.Message_Rbk_Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='route.v2.Message_Rbk_Error.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='route.v2.Message_Rbk_Error.count', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='route.v2.Message_Rbk_Error.level', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='route.v2.Message_Rbk_Error.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=845,
  serialized_end=930,
)


_MESSAGE_RESPONSE_CONFIRMATION = _descriptor.Descriptor(
  name='Message_Response_Confirmation',
  full_name='route.v2.Message_Response_Confirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='commandsNum', full_name='route.v2.Message_Response_Confirmation.commandsNum', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=932,
  serialized_end=984,
)


_MESSAGE_PROPERTIES = _descriptor.Descriptor(
  name='Message_Properties',
  full_name='route.v2.Message_Properties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='route.v2.Message_Properties.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='route.v2.Message_Properties.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=986,
  serialized_end=1034,
)


_MESSAGE_LOADHANDLINGDEVICE = _descriptor.Descriptor(
  name='Message_LoadHandlingDevice',
  full_name='route.v2.Message_LoadHandlingDevice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='route.v2.Message_LoadHandlingDevice.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='full', full_name='route.v2.Message_LoadHandlingDevice.full', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1036,
  serialized_end=1093,
)

_MESSAGE_COMMAND_NORMAL.fields_by_name['commands'].message_type = _MESSAGE_COMMAND
_MESSAGE_COMMAND.fields_by_name['properties'].message_type = _MESSAGE_PROPERTIES
_MESSAGE_COMMAND_ADVANCED.fields_by_name['properties'].message_type = _MESSAGE_PROPERTIES
_MESSAGE_RESPONSE_STATUS.fields_by_name['state'].enum_type = _MESSAGE_RESPONSE_STATUS_VEHICLESTATE
_MESSAGE_RESPONSE_STATUS.fields_by_name['exeState'].enum_type = _MESSAGE_RESPONSE_STATUS_VEHICLEEXECUTINGSTATE
_MESSAGE_RESPONSE_STATUS.fields_by_name['loadHandlingDevices'].message_type = _MESSAGE_LOADHANDLINGDEVICE
_MESSAGE_RESPONSE_STATUS.fields_by_name['errorInfos'].message_type = _MESSAGE_RBK_ERROR
_MESSAGE_RESPONSE_STATUS_VEHICLESTATE.containing_type = _MESSAGE_RESPONSE_STATUS
_MESSAGE_RESPONSE_STATUS_VEHICLEEXECUTINGSTATE.containing_type = _MESSAGE_RESPONSE_STATUS
DESCRIPTOR.message_types_by_name['Message_Command_Normal'] = _MESSAGE_COMMAND_NORMAL
DESCRIPTOR.message_types_by_name['Message_Command'] = _MESSAGE_COMMAND
DESCRIPTOR.message_types_by_name['Message_Command_Advanced'] = _MESSAGE_COMMAND_ADVANCED
DESCRIPTOR.message_types_by_name['Message_Response_Status'] = _MESSAGE_RESPONSE_STATUS
DESCRIPTOR.message_types_by_name['Message_Rbk_Error'] = _MESSAGE_RBK_ERROR
DESCRIPTOR.message_types_by_name['Message_Response_Confirmation'] = _MESSAGE_RESPONSE_CONFIRMATION
DESCRIPTOR.message_types_by_name['Message_Properties'] = _MESSAGE_PROPERTIES
DESCRIPTOR.message_types_by_name['Message_LoadHandlingDevice'] = _MESSAGE_LOADHANDLINGDEVICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message_Command_Normal = _reflection.GeneratedProtocolMessageType('Message_Command_Normal', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_COMMAND_NORMAL,
  '__module__' : 'message_tcs_comm_v2_pb2'
  # @@protoc_insertion_point(class_scope:route.v2.Message_Command_Normal)
  })
_sym_db.RegisterMessage(Message_Command_Normal)

Message_Command = _reflection.GeneratedProtocolMessageType('Message_Command', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_COMMAND,
  '__module__' : 'message_tcs_comm_v2_pb2'
  # @@protoc_insertion_point(class_scope:route.v2.Message_Command)
  })
_sym_db.RegisterMessage(Message_Command)

Message_Command_Advanced = _reflection.GeneratedProtocolMessageType('Message_Command_Advanced', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_COMMAND_ADVANCED,
  '__module__' : 'message_tcs_comm_v2_pb2'
  # @@protoc_insertion_point(class_scope:route.v2.Message_Command_Advanced)
  })
_sym_db.RegisterMessage(Message_Command_Advanced)

Message_Response_Status = _reflection.GeneratedProtocolMessageType('Message_Response_Status', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_RESPONSE_STATUS,
  '__module__' : 'message_tcs_comm_v2_pb2'
  # @@protoc_insertion_point(class_scope:route.v2.Message_Response_Status)
  })
_sym_db.RegisterMessage(Message_Response_Status)

Message_Rbk_Error = _reflection.GeneratedProtocolMessageType('Message_Rbk_Error', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_RBK_ERROR,
  '__module__' : 'message_tcs_comm_v2_pb2'
  # @@protoc_insertion_point(class_scope:route.v2.Message_Rbk_Error)
  })
_sym_db.RegisterMessage(Message_Rbk_Error)

Message_Response_Confirmation = _reflection.GeneratedProtocolMessageType('Message_Response_Confirmation', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_RESPONSE_CONFIRMATION,
  '__module__' : 'message_tcs_comm_v2_pb2'
  # @@protoc_insertion_point(class_scope:route.v2.Message_Response_Confirmation)
  })
_sym_db.RegisterMessage(Message_Response_Confirmation)

Message_Properties = _reflection.GeneratedProtocolMessageType('Message_Properties', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_PROPERTIES,
  '__module__' : 'message_tcs_comm_v2_pb2'
  # @@protoc_insertion_point(class_scope:route.v2.Message_Properties)
  })
_sym_db.RegisterMessage(Message_Properties)

Message_LoadHandlingDevice = _reflection.GeneratedProtocolMessageType('Message_LoadHandlingDevice', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_LOADHANDLINGDEVICE,
  '__module__' : 'message_tcs_comm_v2_pb2'
  # @@protoc_insertion_point(class_scope:route.v2.Message_LoadHandlingDevice)
  })
_sym_db.RegisterMessage(Message_LoadHandlingDevice)


# @@protoc_insertion_point(module_scope)
