# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_rds_door_status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_rds_door_status.proto',
  package='rbk.protocol.rds',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dmessage_rds_door_status.proto\x12\x10rbk.protocol.rds\"y\n\x12Message_DoorStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\ndoorstatus\x18\x02 \x01(\x08\x12\x13\n\x0b\x64oorinplace\x18\x03 \x01(\x08\x12\x19\n\x11\x63onnection_status\x18\x04 \x01(\x08\x12\x11\n\tforbidden\x18\x05 \x01(\x08\"J\n\x13Message_DoorsStatus\x12\x33\n\x05\x64oors\x18\x01 \x03(\x0b\x32$.rbk.protocol.rds.Message_DoorStatusb\x06proto3'
)




_MESSAGE_DOORSTATUS = _descriptor.Descriptor(
  name='Message_DoorStatus',
  full_name='rbk.protocol.rds.Message_DoorStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rbk.protocol.rds.Message_DoorStatus.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='doorstatus', full_name='rbk.protocol.rds.Message_DoorStatus.doorstatus', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='doorinplace', full_name='rbk.protocol.rds.Message_DoorStatus.doorinplace', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connection_status', full_name='rbk.protocol.rds.Message_DoorStatus.connection_status', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='forbidden', full_name='rbk.protocol.rds.Message_DoorStatus.forbidden', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=172,
)


_MESSAGE_DOORSSTATUS = _descriptor.Descriptor(
  name='Message_DoorsStatus',
  full_name='rbk.protocol.rds.Message_DoorsStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='doors', full_name='rbk.protocol.rds.Message_DoorsStatus.doors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=248,
)

_MESSAGE_DOORSSTATUS.fields_by_name['doors'].message_type = _MESSAGE_DOORSTATUS
DESCRIPTOR.message_types_by_name['Message_DoorStatus'] = _MESSAGE_DOORSTATUS
DESCRIPTOR.message_types_by_name['Message_DoorsStatus'] = _MESSAGE_DOORSSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message_DoorStatus = _reflection.GeneratedProtocolMessageType('Message_DoorStatus', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_DOORSTATUS,
  '__module__' : 'message_rds_door_status_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.rds.Message_DoorStatus)
  })
_sym_db.RegisterMessage(Message_DoorStatus)

Message_DoorsStatus = _reflection.GeneratedProtocolMessageType('Message_DoorsStatus', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_DOORSSTATUS,
  '__module__' : 'message_rds_door_status_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.rds.Message_DoorsStatus)
  })
_sym_db.RegisterMessage(Message_DoorsStatus)


# @@protoc_insertion_point(module_scope)
