# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_gnss.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_header_pb2 as message__header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_gnss.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12message_gnss.proto\x12\x0crbk.protocol\x1a\x14message_header.proto\"G\n\x17Message_GnssInstallInfo\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\x0b\n\x03yaw\x18\x04 \x01(\x01\"L\n\x13Message_GnssRefInfo\x12\x11\n\tlongitude\x18\x01 \x01(\x01\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x01\"\x85\x03\n\x0cMessage_GNSS\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.rbk.protocol.Message_Header\x12\x0e\n\x06status\x18\x02 \x01(\x05\x12\t\n\x01x\x18\x03 \x01(\x01\x12\t\n\x01y\x18\x04 \x01(\x01\x12\t\n\x01z\x18\x05 \x01(\x01\x12\x14\n\x0cubx_2d_acc_h\x18\x07 \x01(\x01\x12\x14\n\x0cubx_2d_acc_v\x18\x08 \x01(\x01\x12\x12\n\nubx_3d_acc\x18\t \x01(\x01\x12\x11\n\tlongitude\x18\n \x01(\x01\x12\x10\n\x08latitude\x18\x0b \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x0c \x01(\x01\x12;\n\x0cinstall_info\x18\r \x01(\x0b\x32%.rbk.protocol.Message_GnssInstallInfo\x12\x33\n\x08ref_info\x18\x0e \x01(\x0b\x32!.rbk.protocol.Message_GnssRefInfo\x12\r\n\x05\x65nu_x\x18\x0f \x01(\x01\x12\r\n\x05\x65nu_y\x18\x10 \x01(\x01\x12\x0f\n\x07heading\x18\x11 \x01(\x01\";\n\x0fMessage_AllGNSS\x12(\n\x04gnss\x18\x01 \x03(\x0b\x32\x1a.rbk.protocol.Message_GNSSb\x06proto3'
  ,
  dependencies=[message__header__pb2.DESCRIPTOR,])




_MESSAGE_GNSSINSTALLINFO = _descriptor.Descriptor(
  name='Message_GnssInstallInfo',
  full_name='rbk.protocol.Message_GnssInstallInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='rbk.protocol.Message_GnssInstallInfo.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='rbk.protocol.Message_GnssInstallInfo.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='rbk.protocol.Message_GnssInstallInfo.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='rbk.protocol.Message_GnssInstallInfo.yaw', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=129,
)


_MESSAGE_GNSSREFINFO = _descriptor.Descriptor(
  name='Message_GnssRefInfo',
  full_name='rbk.protocol.Message_GnssRefInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='longitude', full_name='rbk.protocol.Message_GnssRefInfo.longitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='rbk.protocol.Message_GnssRefInfo.latitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='rbk.protocol.Message_GnssRefInfo.altitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=207,
)


_MESSAGE_GNSS = _descriptor.Descriptor(
  name='Message_GNSS',
  full_name='rbk.protocol.Message_GNSS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='rbk.protocol.Message_GNSS.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='rbk.protocol.Message_GNSS.status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='rbk.protocol.Message_GNSS.x', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='rbk.protocol.Message_GNSS.y', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='rbk.protocol.Message_GNSS.z', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ubx_2d_acc_h', full_name='rbk.protocol.Message_GNSS.ubx_2d_acc_h', index=5,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ubx_2d_acc_v', full_name='rbk.protocol.Message_GNSS.ubx_2d_acc_v', index=6,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ubx_3d_acc', full_name='rbk.protocol.Message_GNSS.ubx_3d_acc', index=7,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='rbk.protocol.Message_GNSS.longitude', index=8,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='rbk.protocol.Message_GNSS.latitude', index=9,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='rbk.protocol.Message_GNSS.altitude', index=10,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='install_info', full_name='rbk.protocol.Message_GNSS.install_info', index=11,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ref_info', full_name='rbk.protocol.Message_GNSS.ref_info', index=12,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enu_x', full_name='rbk.protocol.Message_GNSS.enu_x', index=13,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enu_y', full_name='rbk.protocol.Message_GNSS.enu_y', index=14,
      number=16, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heading', full_name='rbk.protocol.Message_GNSS.heading', index=15,
      number=17, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=599,
)


_MESSAGE_ALLGNSS = _descriptor.Descriptor(
  name='Message_AllGNSS',
  full_name='rbk.protocol.Message_AllGNSS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gnss', full_name='rbk.protocol.Message_AllGNSS.gnss', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=601,
  serialized_end=660,
)

_MESSAGE_GNSS.fields_by_name['header'].message_type = message__header__pb2._MESSAGE_HEADER
_MESSAGE_GNSS.fields_by_name['install_info'].message_type = _MESSAGE_GNSSINSTALLINFO
_MESSAGE_GNSS.fields_by_name['ref_info'].message_type = _MESSAGE_GNSSREFINFO
_MESSAGE_ALLGNSS.fields_by_name['gnss'].message_type = _MESSAGE_GNSS
DESCRIPTOR.message_types_by_name['Message_GnssInstallInfo'] = _MESSAGE_GNSSINSTALLINFO
DESCRIPTOR.message_types_by_name['Message_GnssRefInfo'] = _MESSAGE_GNSSREFINFO
DESCRIPTOR.message_types_by_name['Message_GNSS'] = _MESSAGE_GNSS
DESCRIPTOR.message_types_by_name['Message_AllGNSS'] = _MESSAGE_ALLGNSS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message_GnssInstallInfo = _reflection.GeneratedProtocolMessageType('Message_GnssInstallInfo', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_GNSSINSTALLINFO,
  '__module__' : 'message_gnss_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_GnssInstallInfo)
  })
_sym_db.RegisterMessage(Message_GnssInstallInfo)

Message_GnssRefInfo = _reflection.GeneratedProtocolMessageType('Message_GnssRefInfo', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_GNSSREFINFO,
  '__module__' : 'message_gnss_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_GnssRefInfo)
  })
_sym_db.RegisterMessage(Message_GnssRefInfo)

Message_GNSS = _reflection.GeneratedProtocolMessageType('Message_GNSS', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_GNSS,
  '__module__' : 'message_gnss_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_GNSS)
  })
_sym_db.RegisterMessage(Message_GNSS)

Message_AllGNSS = _reflection.GeneratedProtocolMessageType('Message_AllGNSS', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_ALLGNSS,
  '__module__' : 'message_gnss_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_AllGNSS)
  })
_sym_db.RegisterMessage(Message_AllGNSS)


# @@protoc_insertion_point(module_scope)
