# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_rfid.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_header_pb2 as message__header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_rfid.proto',
  package='rbk.protocol',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12message_rfid.proto\x12\x0crbk.protocol\x1a\x14message_header.proto\"m\n\x10Message_RFIDNode\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12,\n\x06header\x18\x03 \x01(\x0b\x32\x1c.rbk.protocol.Message_Header\x12\x10\n\x08strength\x18\x04 \x01(\r\"B\n\x0cMessage_RFID\x12\x32\n\nrfid_nodes\x18\x01 \x03(\x0b\x32\x1e.rbk.protocol.Message_RFIDNodeb\x06proto3'
  ,
  dependencies=[message__header__pb2.DESCRIPTOR,])




_MESSAGE_RFIDNODE = _descriptor.Descriptor(
  name='Message_RFIDNode',
  full_name='rbk.protocol.Message_RFIDNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rbk.protocol.Message_RFIDNode.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='rbk.protocol.Message_RFIDNode.count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='header', full_name='rbk.protocol.Message_RFIDNode.header', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strength', full_name='rbk.protocol.Message_RFIDNode.strength', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=167,
)


_MESSAGE_RFID = _descriptor.Descriptor(
  name='Message_RFID',
  full_name='rbk.protocol.Message_RFID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rfid_nodes', full_name='rbk.protocol.Message_RFID.rfid_nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=235,
)

_MESSAGE_RFIDNODE.fields_by_name['header'].message_type = message__header__pb2._MESSAGE_HEADER
_MESSAGE_RFID.fields_by_name['rfid_nodes'].message_type = _MESSAGE_RFIDNODE
DESCRIPTOR.message_types_by_name['Message_RFIDNode'] = _MESSAGE_RFIDNODE
DESCRIPTOR.message_types_by_name['Message_RFID'] = _MESSAGE_RFID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message_RFIDNode = _reflection.GeneratedProtocolMessageType('Message_RFIDNode', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_RFIDNODE,
  '__module__' : 'message_rfid_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_RFIDNode)
  })
_sym_db.RegisterMessage(Message_RFIDNode)

Message_RFID = _reflection.GeneratedProtocolMessageType('Message_RFID', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_RFID,
  '__module__' : 'message_rfid_pb2'
  # @@protoc_insertion_point(class_scope:rbk.protocol.Message_RFID)
  })
_sym_db.RegisterMessage(Message_RFID)


# @@protoc_insertion_point(module_scope)
